frontend/package-lock.json
frontend/package.json
frontend/webpack.config.js

- close #12 
- 사용하지 않던 ts-loader 삭제
- 타입 체킹을 위해 fork-ts-checker-webpack-plugin 설치 및 적용
- biome 버전 다운그레이드 2.1.1 -> 2.0.6

refactor: 불필요 패키지 정리

---

frontend/src/components/@common/Button.styles.ts
frontend/src/components/@common/Button.tsx
frontend/src/components/@common/variant.ts
frontend/src/stories/Button.stories.tsx

- close #22
- 버튼 컴포넌트를 제작했습니다.
- Primary Button, Secondary Button, Tertiary Button 3가지의 테마를 적용했습니다. 
- props로  `variant`, `text`, `onClick`, `disabled`을 받습니다.
https://github.com/user-attachments/assets/be2d128a-3c6c-45d3-ba0b-a404575f0b1e

feature: Button 컴포넌트 제작

---

frontend/src/@assets/icons/upwardArrow.svg
frontend/src/components/@common/buttons/floatingIconButton/FloatingIconButton.styles.ts
frontend/src/components/@common/buttons/floatingIconButton/FloatingIconButton.tsx
frontend/src/stories/FloatingIconButton.stories.tsx

- close #92 
화면의 하단에 위치하며, 클릭 시 최상단으로 이동하는 기능을 가지는 버튼을 구현했습니다.
- 상단으로 올라가는 기능은 페이지에서 구현해 `onClick`으로 넘겨주면 됩니다.
- 시안과 다른 위치에서 사용될 가능성이 있어, 해당 컴포넌트의 위치는 고정하지 않았습니다.

feature: FloatingIconButton 제작

---

backend/forgather/src/main/java/com/forgather/global/config/SwaggerConfig.java

로컬에서도 실제 서버를 찌르도록 설정되어있어서 로컬과 프로덕션이 다른 url을 가질 수 있도록 설정파일로 분리했습니다.

fix: swagger 서버 url 설정파일 분리

---

backend/forgather/src/main/java/com/forgather/domain/space/util/MetaDataExtractor.java

- close #134
메타데이터 없을 때 `Exception throw` 안하고, null 처리하도록 로직 수정

feat: 메타데이터 누락 핸들링

---

frontend/__test__/hexToRgba.test.ts
frontend/jest.config.js

- close #120 
hexToRgba 유틸 함수의 jest 테스트 코드를 작성했습니다. 
테스트 세팅을 pull 받아 진행했는데 오류가 발생했어요.(스크린샷 첨부)
Jest가 기본적으로 CommonJS 방식으로 설정 파일을 불러오는데, export default 같은 ESM 문법을 만나서 해석에 실패했다는 의미였습니다.
이를 해결하기 위해 `jest.config.js`를 CommonJS 방식으로 변경해서 해결했습니다.

test: hexToRgba 유틸 함수 테스트

---

frontend/__test__/copyLinkToClipboard.test.ts

- close #119 
copyLinkToClipboard 유틸 함수의 jest 테스트 코드를 작성했습니다.

test: copyLinkToClipboard 유틸 함수 테스트

---

frontend/src/pages/demo/DemoHome.styles.ts
frontend/src/pages/demo/DemoHome.tsx
frontend/src/router/router.tsx

- close #154 
- 데모용 임시 메인페이지 생성
- / (메인 루트)로 접속 시 페이지로 이동
- guest의 업로드와 manager의 관리페이지로 이동
- 페이지 확인해주시고 추가적으로 넣어야 할 버튼이 있다면 코멘트 부탁드립니다! 🫡

feature: 데모용 임시 메인페이지 제작

---

frontend/.gitignore
frontend/__test__/parsedImagePath.test.ts
frontend/src/utils/parsedImagePath.ts

- close #164 
- parsedImagePath에서 확장자가 없는 경우를 찾지 못하는 오류 수정
- parsedImagePath의 테스트 커버리지 충족

test: parsedImagePath의 테스트 커버리지 충족

---

frontend/src/components/@common/buttons/floatingIconButton/FloatingIconButton.styles.ts
frontend/src/pages/guest/imageUploadPage/ImageUploadPage.styles.ts
frontend/src/pages/manager/spaceHome/SpaceHome.styles.ts

- close #179
- FloatingIconButton의 위치를 최우단으로 정렬
- 해당 버튼을 사용하는 `ImageUploadPage`, `SpaceHome` 페이지에서 수정
- 최상단으로 이동시키는 FloatingIconButton 그라데이션 수정
- filter -> box-shadow으로 변경

fix: FloatingIconButton 스타일 수정

---

frontend/src/utils/parsedImagePath.ts

- close #183 
- parsedImagePath에 heic, heif, gif 확장명을 추가했습니다.
- 지금은 heic 등의 다른 형식을 모두 jpg로 바꿔서 상관없지만, 나중에 원본을 제공할 때 생길 수 있는 문제입니다.

fix: parsedImagePath에 heic, heif, gif 추가

---

frontend/src/hooks/@common/useFileUpload.ts
frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
frontend/src/utils/isValidFileType.ts

- close #186
https://github.com/user-attachments/assets/6415c829-8e32-46a3-b18b-0dc764358731
- 용량이슈로 클릭 이벤트일 때 alert를 띄우는 것은 안올라가지만, 동일하게 적용됩니다.
- useFile hook이 기존에는 image 형식에만 대응할 수 있도록 되어 있는데, 확장성을 고려하여 fielType을 받아서 처리할 수 있도록 구현하였습니다.
- 현재 파일의 타입이 유효한지 검사하는 util을 추가하였습니다.
- 추후 errorToast를 구현할 것을 대비하여, useFileUpload에서 직접 alert를 주기보다는 errorMessage를 export하도록 수정하였습니다.
그래서 uploadPage에 useEffect가 존재하지만, 추후 없어질 예정입니다.

fix: 이미지 형식이 아닌 파일 제한

---

frontend/src/components/@common/imageGrid/ImageGrid.styles.ts

- close #191 
- 모바일 환경에서 3 column으로 보일 수 있도록 기준 수정
- 일반적인 모바일 화면: 320px ~ 414px
- 100px × 3 = 300px + gap 고려
- 320px 화면에서도 3개가 들어갈 수 있음
120px에서 100px로 변경했어요.
`grid-template-columns: repeat(auto-fit, minmax(100px, 1fr));`

fix: 모바일 이미지 그리드 열 기준 수정

---

frontend/__test__/useInputLength.test.tsx
frontend/src/components/@common/input/Input.tsx
frontend/src/hooks/@common/useInputLength.ts
frontend/src/pages/demo/DemoHome.tsx
frontend/src/pages/manager/spaceHome/SpaceHome.tsx

- close #51
* iOS에서 maxLength에 도달했을 경우 백스페이스를 두 번 눌러야 입력값이 삭제 되는 문제 원인 발견
* IME 조합 문제로 본질적인 해결 불가하다고 판단, 우회 해결책으로 maxLength에 도달했을 경우 input의 focus를 제거함
[📝노션 문서](https://catkin-chokeberry-f58.notion.site/onCompositionEnd-onCompositionStart-238864a9cb03803b979ff2dc2774e9c7?source=copy_link)
* 해당 이슈가 IME 조합 처리로 인한 문제가 아닌, 로직 측면의 문제일 수 있으니 코드 검토 부탁드립니다
* splicedValue는 UI에 표시되는 값이며, value는 실제 DOM에 반영되는 입력값입니다.
: value 상태만으로도 slice 등의 제어는 가능하지만, UI에 보여줄 값과 DOM에 실제 반영되는 값을 분리함으로써 로직을 더 명확하게 이해할 수 있을 것이라 판단해 나누어 사용했습니다. 이 방식에 대해 어떻게 생각하시는지도 함께 피드백 주시면 감사하겠습니다!

fix: iOS에서 백스페이스를 2번 눌러야 input에 입력된 값이 삭제되는 문제 해결

---

frontend/package.json
frontend/src/pages/landing/LandingPage.styles.ts

- close #303
빌드 명령어 production / development 환경별 분리
```
"build:dev": "webpack --mode development",
"build:prod": "webpack --mode production",
```

feature: 빌드 명령어 dev/prod 환경별 분리

---

frontend/src/components/uploadBox/UploadBox.tsx

- close #321 
- 삭제후 동일 사진 업로드 가능하도록 수정하였습니다.
1. A 사진을 올린다.
2. A 사진을 삭제한다.
3. A 사진을 다시 올린다. ---->>> 가 안됨
input으로서 파일 업로드를 하고 있는데, input입장에서는 같은 파일을 올리는 것이기 때문에 변화가 없다고 판단하고, `onChange`를 발생시키지 않음
input의 value를 초기화해줌

fix: 삭제후 동일 사진 업로드 불가 문제 해결

---

frontend/src/components/@common/overlay/Overlay.tsx
frontend/src/components/layout/statusLayout/StatusLayout.tsx
frontend/src/hooks/@common/useScrollLock.ts
frontend/src/pages/manager/spaceHome/SpaceHome.tsx
frontend/src/styles/global.ts

- close #329
* useScrollLock 훅 생성 - 스크롤을 막고 싶은 컴포넌트 단에서 호출하여 사용 가능
* Overlay 컴포넌트 및 StatusLayout 호출시 스크롤 막음
: Backdrop 위에서 스크롤이 되면서 발생하는 문제 해결

fix: overlay 및 만료/생성이전 페이지에서 스크롤 막기

---

frontend/__test__/checkIsPastDateTime.test.ts
frontend/src/pages/create/funnel/SpaceCreateFunnel.tsx
frontend/src/pages/create/funnelElements/CheckSpaceInfoElement.tsx
frontend/src/utils/checkIsPastDateTime.ts

- close #340 
- 스페이스 생성 시 마지막 검증을 통해 막는 로직보단, 스페이스 생성 시 이미 지난 시간을 요청하는 경우 자동으로 지금 당장 시간으로 변경해주는 것이 사용성이 좋다고 판단
- ex) (4시) 스페이스를 4시1분에 생성 -> 스페이스 확인 페이지에서 5분 대기 -> (4시 5분) 스페이스 생성 완료 버튼 클릭 -> 4시 5분 생성으로 자동 변경
- As Is: 나중에를 누른 상황에서 현재 시간이 선택되지 않았음 (4시인 경우 4시 1분부터 선택 가능)
- To Be: 나중에를 누른 상황에서 현재 시간이 선택됨 (4시인 경우 4시가 선택됨)

refactor: 오픈 시간 이후에 생성 시 지금 당장 생성으로 대체

---

frontend/src/components/@common/imageLayout/imageElement/fakeImageElement/FakeImageElement.styles.ts
frontend/src/components/@common/imageLayout/imageElement/fakeImageElement/FakeImageElement.tsx
frontend/src/components/@common/imageLayout/imageGrid/fakeImageGrid/FakeImageGrid.tsx
frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
frontend/src/stories/FakeImageElement.stories.tsx
frontend/src/stories/FakeImageGrid.stories.tsx

- close #302
- 이미지 그리드 대신 스타일만 입힌 FakeImageGrid, FakeImageElement 컴포넌트 생성
- 사용자가 억지로 전면 오버레이를 삭제한 경우 업로드 박스를 클릭해 업로드를 할 수 있음
- 업로드를 할 수 없는 박스로 대체
- `const shouldShowFakeUploadBox = isNoData || isEarlyTime || isSpaceExpired;`
```tsx
{shouldShowFakeUploadBox ? (
<UploadBox
mainText={''}
uploadLimitText={''}
...
disabled={true} // 비활성화
/>
) : (
<UploadBox
mainText={`함께한 순간을 올려주세요.${hasImages ? '' : '\n사진만 올릴 수 있습니다.'}`}
uploadLimitText={
hasImages ? '' : '한 번에 500장까지 올릴 수 있어요'
}
...
disabled={isUploading}
/>
)}
```
- FakeImageGrid를 구현했지만 적용하려다 아래 이유로 아직 실제코드에 적용하지 않았습니다.
- 이에 대해 굳이 사용해야 할까 의견을 묻고 싶습니다! 🤔
- 다음과 같이 FakeImageGrid가 없어도 이미지가 자동으로 삭제되기 때문에 실제 코드에 적용할 필요가 없어졌다고 판단
- **이전엔 만료된 스페이스의 사진 조회에 에러가 발생하지 않지만, API 응답값의 변경으로 사진 조회에 400 에러가 발생하기 때문**

feature: 스페이스를 사용할 수 없는 경우 컴포넌트 대체

---

backend/forgather/src/main/java/com/forgather/domain/space/repository/PhotoRepository.java
backend/forgather/src/main/java/com/forgather/domain/space/service/AwsS3Cloud.java
backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java

- close #335 
- 썸네일 사진도 함께 삭제
-  원본 사진 + 썸네일 사진 2장(모바일, 데스크탑)
- `@Query`를 사용한 bulk delete에서 `deleteAll()`로 변경
- 성능 차이가 없음. 지연 쓰기로 인해 가장 비용이 큰 I/O 작업은 많이 일어나지 않아 나가는 쿼리의 for문을 통해 delete쿼리를 날려 나가는 쿼리 수만 많아보이지. 성능 상 차이는 없음
- 오히려 `deleteAll()`이 더 안정적
- S3 삭제 로직 변경
- `S3Client#deleteObjects`는 1,000건 까지 삭제 가능 -> 1,001건 부터 삭제 요청이 실패 -> 1,000건 넘어가면 나누어 삭제

feature: 사진 삭제 시 썸네일 삭제

---

backend/forgather/build.gradle
backend/forgather/src/main/java/com/forgather/global/auth/client/KakaoAuthClient.java
backend/forgather/src/main/java/com/forgather/global/auth/client/KakaoTokenDto.java
backend/forgather/src/main/java/com/forgather/global/auth/scheduler/KakaoPublicKeyScheduler.java
backend/forgather/src/main/java/com/forgather/global/auth/scheduler/RefreshTokenRemoveScheduler.java
backend/forgather/src/main/java/com/forgather/global/auth/util/JwtParser.java

기존에는 카카오 로그인 시 반환되는 id_token jwt의 시그니처를 검증하지 않고 페이로드를 그대로 가져와 사용하고 있습니다.
카카오의 공개키를 가져와 id_token을 검증하도록 수정했습니다.
---
참고 내용
JWKS 엔드포인트에서 키 조회 (JwtParser.java:62-65):
https://kauth.kakao.com/.well-known/jwks.json
- Kakao가 공개적으로 제공하는 키 저장소
- 여러 개의 RSA 공개키들을 JSON 형태로 제공
- 각 키는 고유한 kid(Key ID)를 가짐
RSA 공개키 복원 (JwtParser.java:74-82):
1. JWT 헤더의 kid와 일치하는 키 찾기
2. JWK 형식의 n(modulus), e(exponent) 추출
3. Base64URL 디코딩 → 바이트 배열 → BigInteger 변환
4. RSAPublicKeySpec 생성 → Java PublicKey 객체 생성
JWT 구조:
헤더.페이로드.시그니처
검증 과정 (JwtParser.java:46-50):
1. JJWT 라이브러리 사용: Jwts.parser().verifyWith(publicKey)
2. 내부 동작:
- 헤더.페이로드 부분을 SHA256으로 해시
- 시그니처를 공개키로 복호화
- 두 값이 일치하는지 확인
RSA 디지털 서명:
- Kakao가 개인키로 서명 생성: signature = RSA_sign(private_key, 
hash(header.payload))
- 클라이언트가 공개키로 검증: RSA_verify(public_key, signature, …

feat: 카카오 정보 접근 시 jwt 시그니처 검증

---

backend/forgather/src/main/java/com/forgather/domain/space/dto/SpaceResponse.java
backend/forgather/src/main/java/com/forgather/domain/space/model/Space.java

- close #443
스페이스 단건 조회 시 업로더 수와 업로드된 사진 수를 함께 반환하도록 필드를 추가했습니다.
이후 스페이스 목록 조회 시에도 통계 정보(guestCount, photoCount)를 추가해야 합니다.

feat: 스페이스 정보 조회 시 통계 정보 추가

---

frontend/src/constants/messages.ts
frontend/src/hooks/useDownload.ts
frontend/src/hooks/useWebShareAPI.ts
frontend/src/pages/create/funnelElements/CheckSpaceInfoElement.tsx
frontend/src/pages/guest/sharePage/SharePage.tsx
frontend/src/pages/manager/spaceHome/SpaceHome.tsx
frontend/src/utils/checkIsIos.ts
frontend/src/validators/share.validator.ts

- close #391
- Web Share API를 사용할 수 있는 커스텀 훅
- share를 이용해 WebShare API를 사용할 수 있음
- ios의 경우 사진 한 장을 다운받은 뒤 갤러리에 저장하기 위해 한번 더 들어가야 하는 불편함이 있음
- 단일 다운로드 시 Web Share로 바로 넘어가게 함으로써 필요한 depth를 감소
- Web Share API를 이용해 title, text, url을 공유할 수 있음
- 공유한 결과(카카오톡)

feature: Web Share API 연동

---

frontend/src/hooks/useFileUpload.ts

- close #473 
- 업로드가 실패한 경우에 대해서 다시 throw 하도록 수정하였습니다.
- 놀랍게도 처리하지 않고 있었는데, ~클린코드를 버리고~ 기능을 택했습니다.
- s3에 업로드 실패
- 서버에게 성공 알림 실패한 경우
- presigned-url 발급 오류

fix: 업로드 중 오류가 발생한 경우 

---

frontend/src/apis/services/space.service.ts
frontend/src/hooks/@common/useGraphemeInput.ts
frontend/src/hooks/useSpaceInfo.ts
frontend/src/pages/manager/settings/SettingsPage.tsx

- close #509
스페이스 정보 수정이 가능해졌습니다.
- 스페이스 이름, 시작 날짜, 시작 시간 중 변경이 있는 부분만 서버로 전송합니다.
- 만료/시작된 스페이스는 이름만 수정 가능하도록 분기처리했습니다. 
- 예정된 스페이스는 3가지 모두 변경 가능합니다. 
- 요청이 성공하면 info 타입의 토스트가 뜹니다. 
https://github.com/user-attachments/assets/ce16f30b-8886-4270-bc09-1561e2e9829d
https://github.com/user-attachments/assets/97caa061-f011-4263-a315-e0365b0f52e1

refactor: 스페이스 정보 페이지의 수정 로직 변경

---

frontend/src/apis/http.ts
frontend/src/hooks/useDownload.ts

- close #548
[트러블슈팅문서](https://www.notion.so/presigned-url-25a864a9cb03804c849fdec3146ed037?source=copy_link)
업로드 시 헤더에 다음 2개를 추가
* Content-Control : 브라우저나 중간 프록시(Cache 서버)가 이 응답을 캐싱하지 않도록 강제하는 지시어 (다운로드 전용 컨텐츠에 사용함)
* Content-Disposition attachment: 응답을 브라우저가 화면에 표시하지 않고 파일 다운로드로 처리하도록 지시 (특정 브라우저에선 a download가 팝업이 뜨는 것으로 연결될 수 있음, 이를 방지하기 위함)
```typescript
headersOverride: {
"Content-Type": file.type || "application/octet-stream",
"Cache-Control": "no-store",
"Content-Disposition": `attachment; filename*=UTF-8''${encodeURIComponent(file.name)}`,
"x-amz-tagging":
"Service=techcourse&Role=techcourse-etc&ProjectTeam=PhotoGather",
},
```
해당 설정을 적용한 이미지는 다운로드에 오류 X
해당 설정을 적용하지 않은 이미지는 간헐적으로 다운로드에 오류가 생기는 문제 확인

fix: 다운로드 기능 안정화를 위한 업로드 헤더 수정

---

frontend/public/index.html
frontend/src/apis/createHeaders.ts
frontend/src/apis/http.ts
frontend/src/pages/manager/dashboard/DashboardPage.tsx

- close #558
백엔드에서 설정한 '한 스페이스에서 가질 수 있는 최대 용량'은 `10GB`입니다. 
기존의 MB 단위로 표기하면 '1024MB'가 되어 가독성을 해치는 문제가 있었습니다.(런칭 페스티벌에 받은 피드백)
이에 따라 MB -> GB로 변경했습니다. 
전
후
백엔드 측에서 요청을 부탁한 사항입니다.
기존에는 request body 로그 파일을 보면 body가 없는데도 로그들이 쌓인 것을 확인 가능했으며, request body가 없는 경우 header에 content-type를 없애달라는 요청이 있었습니다.
따라서 GET 메서드일 때는 `Content-Type` 헤더를 설정하지 않도록 조건을 추가했습니다.
이전에는 OG 이미지가 `GitHub user-attachments URL`을 사용하고 있었는데, 이는 외부 접근이 제한될 수 있다는 문제가 있었습니다.
OG 이미지는 공개적으로 접근 가능한 URL이어야 한다고 하여 [포게더 WIKI](https://github.com/woowacourse-teams/2025-PhotoGather/wiki)에 이미지를 추가했고, 이 이미지 경로를 사용하도록 변경했습니다.
배포 후에 테스트가 가능한 문제라 우선 코드만 바꿔두었습니다.

refactor: 스페이스 용량 단위 변경

---

frontend/package-lock.json
frontend/package.json
frontend/src/hooks/@common/useLocalFile.ts
frontend/src/utils/heic.ts

- close #564 
자세한 문서는 [노션 참고](https://www.notion.so/Chrome-heic-265864a9cb03807ea002fa26d0d1139b?source=copy_link)해주세요!!
- 크롬 및 대부분의 브라우저가 HEIC를 직접 디코딩하지 못해 미리보기가 깨지는 문제가 있었습니다.
- iOS: 업로드 시 자동으로 jpeg 변환 → 미리보기 정상 동작
- Android/PC(except Safari): heic 그대로 업로드 → 브라우저에서 해석 불가 → 미리보기 깨짐
- 기존: URL.createObjectURL(file) 로 blob URL 생성 후 <img> 태그에 바인딩
- 문제: heic는 브라우저에서 디코딩 불가 → 렌더링 실패
- 해결: heic 파일 감지 후 heic2any 라이브러리로 jpeg 변환 → 변환된 blob으로 미리보기 생성

fix: heic -> jpeg로 변환하여 blob url을 추출할 수 있도록 수정

---

backend/forgather/src/main/java/com/forgather/domain/guest/repository/GuestRepository.java
backend/forgather/src/main/java/com/forgather/domain/space/repository/HostRepository.java
backend/forgather/src/main/java/com/forgather/domain/space/repository/PhotoRepository.java
backend/forgather/src/main/java/com/forgather/domain/space/repository/SpaceRepository.java

- close #611 
각 `Repositoy#findById` 디폴트 메서드에 Long 타입 파라미터인 id의 null 검증 로직을 추가했습니다.

refactor: Repository의 default 메서드 null 대응

---

frontend/__test__/parsedImagePath.test.ts
frontend/src/components/@common/modal/photoModal/PhotoModal.tsx
frontend/src/hooks/useDownload.ts
frontend/src/hooks/usePhotosBySpaceCode.ts
frontend/src/pages/mypage/MyPage.tsx
frontend/src/utils/buildImageUrl.ts
frontend/src/utils/parsedImagePath.ts
frontend/src/utils/removeWhiteSpace.ts
frontend/webpack.config.js

- close #597
- 단건조회 이미지 조회가 안되는 문제 해결
- 전체 다운로드 / 단일 다운로드가 안되는 문제 해결
- env 파일은 동일
✅ 서버에서 전송되는 url 형태
```typescript
photogather/dev/contents/d51ea4707d/cd5ab532-9eed-42c2-8675-c39f2622e68c.jpeg
```
유틸 함수를 통해 url 조합
* parseImagePath: url 중 "photogather/dev/contents/" 삭제
* buildOriginalImageUrl: env 파일에 있는 imageBaseUrl에 parseImagePath로 파싱한 url 합성

fix: 단건 조회 image-url 변경

---

frontend/src/apis/http.ts
frontend/src/apis/services/auth.service.ts
frontend/src/constants/constraints.ts
frontend/src/constants/keys.ts
frontend/src/hooks/@common/useAuth.ts
frontend/src/hooks/@common/useAuthActions.ts
frontend/src/hooks/@common/useAuthConditionTasks.ts
frontend/src/hooks/domain/useKakaoAuth.ts
frontend/src/pages/demo/DemoHome.tsx
frontend/src/pages/landing/LandingPage.tsx
frontend/src/pages/logout/LogoutPage.tsx
frontend/src/utils/authCookieManager.ts

- close #599 
- refresh 토큰 로직을 추가했습니다.
- access 만료 시 "이름" 마이페이지가 보이던 문제를 해결했습니다.
- 기존 useKakaoAuth에 몰려있던 로그인 관련 로직을 여러 모듈로 분리했습니다.
- kakao가 아니라 다른 경우로도 로그인할 경우를 생각했습니다.
- useAuth: 로그아웃(useNavigate를 사용하므로 훅으로 분리)
- authCookieManager: auth 관련 토큰을 담고 삭제하는 로직
- [정리 문서](https://catkin-chokeberry-f58.notion.site/26f864a9cb0380ada645cc48fe06db52?source=copy_link)

fix: 로그인 refresh 로직 추가
