woowacourse-teams/2025-PhotoGather

- backend/forgather/build.gradle
- backend/forgather/src/main/java/com/forgather/ForgatherApplication.java
- backend/forgather/src/main/java/com/forgather/domain/model/BaseTimeEntity.java
- backend/forgather/src/main/java/com/forgather/domain/space/controller/SpaceController.java
- backend/forgather/src/main/java/com/forgather/domain/space/dto/CreateSpaceRequest.java
- backend/forgather/src/main/java/com/forgather/domain/space/dto/CreateSpaceResponse.java
- backend/forgather/src/main/java/com/forgather/domain/space/model/Space.java
- backend/forgather/src/main/java/com/forgather/domain/space/repository/SpaceRepository.java
- backend/forgather/src/main/java/com/forgather/domain/space/service/SpaceService.java
- backend/forgather/src/main/java/com/forgather/domain/space/util/RandomCodeGenerator.java
- backend/forgather/src/main/resources/application.yml
- backend/forgather/src/test/java/com/forgather/acceptance/AcceptanceTest.java
- backend/forgather/src/test/java/com/forgather/acceptance/SpaceAcceptanceTest.java
- backend/forgather/src/test/java/com/forgather/domain/space/util/RandomCodeGeneratorTest.java
> feature: 스페이스 생성 및 링크 응답

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/index.styles.ts
- frontend/src/styles/theme.ts
- frontend/src/types/emotion.d.ts
- close #28 
* emotion/css -> emotion/styled로 라이브러리 변경
* ThemeProvider 적용
* `emotion.d.ts` 로 theme 타입 정의
> chore: emotion/styled 라이브러리로 교체

- frontend/src/App.tsx
- frontend/src/styles/theme.ts
- frontend/src/types/emotion.d.ts
- close #31 
* 타이포그래피 font-weight 오기입 수정
> fix: 타이포그래피 font-weight 수정

- frontend/src/App.tsx
- frontend/src/components/input/Input.styles.ts
- frontend/src/components/input/Input.tsx
- frontend/src/constants/contraints.ts
- frontend/src/hooks/useInputLength.ts
- frontend/src/stories/Input.stories.tsx
- frontend/src/styles/global.ts
- frontend/src/styles/theme.ts
- frontend/src/types/emotion.d.ts
- close #25 
* input 컴포넌트 UI 제작
* 입력값 글자수 인식 (영어, 한글 - 조합형 글자) 대응
* 에러 발생시`border` 스타일링 및 에러메세지 생성
> feature: input 컴포넌트 제작

- backend/forgather/src/main/resources/schema.sql
- close #50 
- `schema.sql` 추가
> feature: schema.sql 추가

- frontend/src/components/@common/Button.styles.ts
- frontend/src/components/@common/Button.tsx
- frontend/src/components/@common/CircularLabelButton/CircularLabelButton.styles.ts
- frontend/src/components/floatingActionButton/FloatingActionButton.styles.ts
- frontend/src/copyButton/CopyButton.styles.ts
- frontend/src/styles/global.ts
- close #49 
* button의 공통 속성을 global.ts에 정의
* button background color를 설정하였습니다.
* button의 css에 background -> background-color로 공통화하였습니다.
> refactor: button 공통 css 속성을 global.ts에 정의

- backend/forgather/src/main/java/com/forgather/domain/space/controller/PhotoController.java
- backend/forgather/src/main/java/com/forgather/domain/space/dto/CreateSpaceRequest.java
- backend/forgather/src/main/java/com/forgather/domain/space/dto/CreateSpaceResponse.java
- backend/forgather/src/main/java/com/forgather/domain/space/model/Space.java
- backend/forgather/src/main/java/com/forgather/domain/space/repository/SpaceRepository.java
- backend/forgather/src/main/java/com/forgather/domain/space/service/AwsS3Service.java
- backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java
- backend/forgather/src/main/java/com/forgather/domain/space/service/SpaceService.java
- backend/forgather/src/main/resources/data.sql
- backend/forgather/src/main/resources/schema.sql
- backend/forgather/src/test/java/com/forgather/acceptance/PhotoAcceptanceTest.java
- backend/forgather/src/test/java/com/forgather/acceptance/SpaceAcceptanceTest.java
- close #67
- `HostCode`와 `GuestCode` 개념 삭제 -> `SpaceCode` 로 통일
- 코드 내에서 쓰인 관련 용어 수정
- DB 구조 수정`(schema.sql, data.sql)`
> refactor: spaceCode로 코드 개념 통일

- backend/forgather/src/main/java/com/forgather/global/config/CorsProperties.java
- backend/forgather/src/main/java/com/forgather/global/config/WebConfig.java
- close #108 
위와 같이 뜨는 상황 해결
cors관련 세부 설정은 application.yml로 분리
> feature: CORS 설정 적용

- backend/forgather/src/main/java/com/forgather/global/config/SwaggerConfig.java
스웨거 서버 url이 http로 되어있어서 cors 발생하여 https로 수정했습니다.
> fix: swagger server url 프로토콜 수정

- backend/forgather/src/main/java/com/forgather/global/config/SwaggerConfig.java
> fix: swagger 루트 도메인 변경

- frontend/__test__/createImageErrorHandler.test.tsx
- frontend/jest.config.js
- close #121 
- createImageErrorHandler 유틸 함수에 대한 테스트를 작성했습니다.
> test: createImageErrorHandler 유틸 함수 테스트

- frontend/public/index.html
- frontend/src/styles/global.ts
- close #142
- 이슈에 있는 설명 문구 버그 수정
- 타이틀 변경
- global 스타일로 `font-synthesis: none;` 설정
> fix: 설명 문구 버그 수정 및 전체 스타일 변경

- .github/workflows/backend-test.yml
> feature: 백엔드 깃허브 테스트 workflow 구현

- .github/workflows/backend-test.yml
> feature: 백엔드 깃허브 테스트 workflow 수정

- .github/workflows/frontend-ci.yml
- frontend/package.json
- frontend/src/index.tsx
- frontend/src/utils/copyLinkToClipboard.ts
- close #148 
- biome lint, prettier lint 명령어 추가
- 프론트엔트 github actions CI 파일 추가
> chore: 프론트엔드 CI 추가

- backend/forgather/deploy/appspec.yml
- backend/forgather/deploy/buildspec.yml
- backend/forgather/deploy/deploy.sh
> feat: CI/CD 설정 파일 추가 

- frontend/src/components/layout/Layout.styles.ts
- frontend/src/pages/complete/DownloadCompletePage.tsx
- frontend/src/pages/complete/SpaceCreatedCompletePage.tsx
- frontend/src/pages/complete/UploadCompletePage.tsx
- frontend/src/router/router.tsx
- close #162 
- 각종 상황에 따른 완료 페이지 구현
- `DownloadCompletePage`
- `SpaceCreatedCompletePage`
- `UploadCompletePage`
- 라우터 처리 되어있어요.
> feature: Complete 레이아웃 기반 페이지 제작

- backend/forgather/deploy/buildspec.yml
- backend/forgather/deploy/deploy.sh
> fix: ci 설정 파일 수정

- backend/forgather/src/main/java/com/forgather/global/config/WebConfig.java
> fix: 페이징 번호 1번을 기본으로 설정

- frontend/src/hooks/@common/useFileUpload.ts
- frontend/src/hooks/useDownload.ts
- frontend/src/pages/guest/imageUploadPage/ImageUploadPage.styles.ts
- frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
- frontend/src/pages/manager/spaceHome/SpaceHome.tsx
- close #194 
- 다운로드, 업로드할 때, 스피너, navigate 연결 완료
🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
> feat: 업로드 페이지 로딩 스피너, 라우팅 추가

- frontend/src/components/leftTimeInformationBox/LeftTimeInformationBox.tsx
- frontend/src/constants/debugMessages.ts
- frontend/src/hooks/@common/useTimer.ts
- frontend/src/stories/LeftTimeInformationBox.stories.tsx
- frontend/src/types/timer.type.ts
- frontend/src/utils/formatDate.ts
- frontend/src/utils/formatTime.ts
- frontend/src/utils/formatTimer.ts
- frontend/src/utils/isParsableToDate.ts
- close #221 
https://github.com/user-attachments/assets/fec5e4f5-1270-4c24-b8a7-3c56d9f6654d
- 현재 시간을 기준으로 남은 시간을 계산하는 useTimer 커스텀 훅을 구현하였습니다.
- UI 단에서 바로 사용할 수 있도록, 남은 시간을 00:00:00 형식으로 포맷팅해주는 formatTimer 유틸 함수를 분리하였습니다.
- 24시간 이상 남은 경우 "0일" 형식으로 day 단위를 함께 표기합니다.
``` js
const returnValue = formatDate(value)
// 1일
// 12:25:48
```
- 현재 날짜 및 시간(오전/오후)을 반환하는 formatDate 유틸 함수를 추가하였습니다.
- date, time 형태로 각각 반환됩니다.
``` js
const {date, time} = formatDate(value)
```
- LeftTimeInformationBox 컴포넌트에서 불필요한 주석을 정리하였습니다.
> feature: 타이머 훅 제작

- frontend/src/styles/@common/Overlay.styles.ts
- frontend/src/styles/theme.ts
- close #235
- Overlay에 사용할 스타일을 작성했습니다.
> design: Overlay 스타일 작성

- frontend/src/hooks/@common/useFileUpload.ts
- frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
- close #240
- develop이 실행되지 않는 문제를 해결했습니다.
- 각자 실행되는지 확인하시고 Approve 부탁드립니다!
> fix: develop이 실행되지 않는 오류 해결

- backend/forgather/deploy/appspec-dev.yml
- backend/forgather/deploy/appspec-prod.yml
- backend/forgather/deploy/buildspec.yml
- backend/forgather/deploy/deploy-dev.sh
- backend/forgather/deploy/deploy-prod.sh
> deploy: 운영/개발 서버에 따른 배포 구성 파일 분리

- backend/forgather/deploy/appspec-dev.yml
- backend/forgather/deploy/appspec.yml
- backend/forgather/deploy/buildspec-dev.yml
- backend/forgather/deploy/buildspec-prod.yml
- backend/forgather/deploy/deploy-dev.sh
- backend/forgather/deploy/deploy-prod.sh
> deploy: appspec 단일화

- frontend/src/hooks/@common/useFileUpload.ts
- frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
- frontend/src/types/file.type.ts
- close #262 
업로드 전 사진 삭제 잘 구현이 됩니다!! 다들 한번씩 확인 부탁드려요 :)
그냥 id 추가하고, id에 따라 previewData, uploadFile 을 각각 삭제하도록 하였습니다 ~~
> feature: 업로드시 사진 삭제 구현

- backend/forgather/src/main/java/com/forgather/domain/space/controller/PhotoController.java
> fix: 사진 선택 및 압축 다운로드 HTTP 메서드 변경 

- backend/forgather/src/main/java/com/forgather/domain/space/model/Photo.java
메타데이터 촬영 시간 관련 NPE 방어 로직 추가
- 급한 패치가 필요하므로 bypass-merge 함.
> fix: 메타데이터 NPE 방어 로직 추가

- frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
- close #305
업로드 숨겨진 버튼 구현
https://github.com/user-attachments/assets/0ad234d3-5a62-4364-819c-b86d415d3bad
> refactor: 업로드 페이지 임시로 오픈 전 overlay 풀 수 있도록 수정

- backend/forgather/src/main/java/com/forgather/domain/space/service/SpaceService.java
> fix: 만료된 space도 정보 조회 가능하도록 수정

- frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
- frontend/src/pages/manager/spaceHome/SpaceHome.tsx
- frontend/src/styles/theme.ts
- close #325
변경전 -> 변경 후
<div>
</div>
* floatButton의 zindex를 backdrop보다 낮도록 수정
> fix: floatButton의 zindex 값 수정

- frontend/public/index.html
- frontend/src/components/header/spaceHeader/SpaceHeader.tsx
- frontend/src/components/photoSelectionToolBar/PhotoSelectionToolBar.tsx
- frontend/src/hooks/@common/useLandingScroll.ts
- frontend/src/hooks/useGoogleAnalytics.ts
- frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
- frontend/src/pages/landing/LandingPage.tsx
- frontend/src/pages/manager/spaceHome/SpaceHome.tsx
- frontend/src/utils/googleAnalytics/track.ts
- close #323 
[노션에서 결론만 보기](https://www.notion.so/GA-24d864a9cb03800789f3cddeee83dd9f?source=copy_link#24d864a9cb0380069260c086957ae011)
useGoogleAnalytics에서 아래와 같이 불러오고 있었습니다.
``` js
if (!MEASUREMENT_ID) {
console.log('🚫 로컬 환경 - GA4 초기화 건너뜀');
return;
}
ReactGA.initialize(MEASUREMENT_ID);
console.log('✅ GA4 초기화 완료:', MEASUREMENT_ID);
````
개발자 모드를 켜서 트래픽확인하기 위해서는 아래의 코드로 변경해주고,
.env.production에 있던 GOOGLE_TAG_ID를 .env에 추가해주셔야 합니다.
그리고 아래 주석 처리된 코드를 해제해주셔야 합니다.
_그리고 기존 코드는 잠시 주석처리해주세요!_
(아래 코드로 대체하지 않은 이유는 진짜 배포해서 잘 굴러가면 없애보려고요)
``` js
/* 개발모드에서 GA 트래픽확인하기 위해서는 아래 코드 대신 사용 */
/* const isDev = process.env.ENVIRONMENT === 'development';
if (!MEASUREMENT_ID) {
console.log('🚫 GA4 측정 ID 없음 - 초기화 생략');
return;
}
if (isDev) {
ReactGA.initialize(MEASUREMENT_ID, {
// 타입에 맞는 필드만 전달 (원하면 testMode: …
```
> feature: GA 트래킹 추가

- frontend/src/pages/guest/imageUploadPage/ImageUploadPage.tsx
- frontend/src/pages/manager/spaceHome/SpaceHome.tsx
- frontend/src/stories/LoadingLayout.stories.tsx
- close #354 
더미 텍스트로 작성되어 있던 로딩 텍스트를 다음과 같이 변경했습니다.
1. 추억 담는 중
2. 선물 상자 포장하는 중
3. 배달 가는 중
4. 당신에게 전달 중
https://github.com/user-attachments/assets/9f9cf73e-babf-4b25-ad93-1dcd5b4eee3b
> feature: 로딩 텍스트 UX 라이팅

- frontend/src/hooks/useGoogleAnalytics.ts
> refactor: GA 초기화 코드 변경

- backend/forgather/src/main/java/com/forgather/domain/space/dto/CreateSpaceRequest.java
- backend/forgather/src/main/java/com/forgather/domain/space/model/Space.java
- backend/forgather/src/test/java/com/forgather/domain/space/model/SpaceTest.java
- backend/forgather/src/test/java/com/forgather/domain/space/service/SpaceServiceTest.java
- close #310 
- 스페이스 이름 10자 초과 검증
- 스페이스 오픈 시각 검증 (과거 시점에 열 수 없도록)
> feature: 각종 도메인 검증 추가

- frontend/src/utils/buildImageUrl.ts
> refactor: 썸네일 이미지 파싱 수정

- frontend/src/pages/landing/LandingPage.tsx
- close #371 
기존 SNS 로그인 버리고 생성하기 버튼 추가
> feature: 스페이스 생성 버튼 추가

- frontend/src/pages/landing/LandingPage.tsx
> refactor: 버튼과 섹션 위치 수정

- backend/forgather/deploy/deploy-dev.sh
- backend/forgather/deploy/deploy-prod.sh
> fix: nohup의 표준 리다이렉트를 /dev/null로 이동

- backend/forgather/src/main/java/com/forgather/global/auth/resolver/HostIdArgumentResolver.java
아직 로그인이 제대로 반영되지 않은 상황에서 필수로 로그인 정보를 받아야 하던 기존 로직 수정.
내일까지 개선해서 새로 PR 올리겠습니다.
> fix: 로그인 정보 없을 시 정상 처리되도록 수정

- frontend/src/hooks/domain/useKakaoAuth.ts
- frontend/src/pages/demo/DemoHome.tsx
- frontend/src/pages/landing/LandingPage.tsx
- frontend/src/pages/login/LoginPage.tsx
> fix: login error 해결

- frontend/src/components/donutGraph/DonutGraph.styles.ts
- frontend/src/components/donutGraph/DonutGraph.tsx
- frontend/src/stories/DonutGraph.stories.tsx
- close #442 
- 용량 표시에 필요한 DonutGraph를 구현했습니다.
> feature: DonutGraph 구현

- frontend/src/hooks/@common/useLocalFile.ts
- frontend/src/hooks/useFileUpload.ts
- frontend/src/stories/SpaceManagerImageElement.stories.tsx
- frontend/src/stories/SpaceManagerImageGrid.stories.tsx
- frontend/src/types/file.type.ts
- frontend/src/types/photo.type.ts
- close #460 
- uploadFile에 capacityValue를 추가해서 api 전달하도록 수정
> feature: uploadFile에 capacityValue 필드 추가

- frontend/src/hooks/useDownload.ts
> fix: 로딩이 움직이지 않는 문제 해결

- frontend/src/hooks/useDownload.ts
- frontend/src/hooks/useGuestNickName.tsx
- close #476
* guesId를 저장하는 위치를 로컬스토리지에서 쿠키로 변경
* 쿠키에서 하루 뒤에 삭제되도록 설정
> fix: 로컬스토리지에서 쿠키로 변경

- frontend/src/components/@common/modal/Modal.common.styles.ts
- frontend/src/components/@common/modal/inputModal/InputModal.tsx
- frontend/src/components/@common/modal/photoModal/PhotoModal.styles.ts
- frontend/src/components/layout/loadingLayout/LoadingLayout.tsx
- frontend/src/pages/manager/spaceHome/SpaceHomePage.styles.ts
- frontend/src/pages/manager/spaceHome/SpaceHomePage.tsx
- frontend/src/styles/@common/BackDrop.styles.ts
- close #483
*  닉네임 엔터 업로드 기능 추가
*  로딩이 뜰 시 스크롤이 되지 않도록 설정 (useScrollLock 훅 사용)
* 모달 크기 수정 (min-width를 100px 로 설정)
https://github.com/user-attachments/assets/c7c56325-5a40-4b5c-b824-01d415fc02e4
> feature: enter 업로드 기능 추가 및 디자인 점검

- backend/forgather/src/main/java/com/forgather/domain/space/model/Space.java
- 사진이 올라간 Space 삭제 때 SpaceContent에 cascade, orphanRemoval 설정이 없어서 문제 발생
> fix: 사진이 올라간 스페이스 삭제 API Cascade 문제 수정

- frontend/src/pages/create/funnelElements/agreementElement/AgreementElement.styles.ts
- frontend/src/pages/create/funnelElements/agreementElement/AgreementElement.tsx
- frontend/src/pages/policies/PrivacyConsentPage.tsx
- frontend/src/pages/policies/TermsOfServicePage.tsx
- close #519 
- 약관 동의 퍼널에서 제목을 클릭 할 수 있도로 수정
- 약관 동의 페이지에서 퍼널로 돌아갈 수 있는 버튼 생성
> refactor: 약관 동의 수정

- frontend/src/pages/create/funnel/SpaceCreateFunnel.tsx
> fix: 퍼널 순서 정상화

- frontend/src/constants/routes.ts
- frontend/src/router/router.tsx
> fix: router 원상복구

- frontend/src/hooks/useSpaceCodeFromPath.ts
> fix: 라우터 수정

- frontend/src/hooks/useDownload.ts
> fix: 전체 다운로드가 안되는 오류 해결

- backend/forgather/src/main/java/com/forgather/domain/space/service/PhotoService.java
- backend/forgather/src/main/java/com/forgather/domain/space/service/SpaceService.java
- backend/forgather/src/test/resources/application.yml
- 로그인 사용자도 공개 허용된 스페이스에 접근해 일부 호스트 권한을 사용할 수 있도록 변경
> fix: 로그인한 상태에서도 공개 스페이스에 접근 가능하도록 변경

- backend/forgather/src/main/resources/logback-spring.xml
> fix: rolling 파일 패턴 충돌 해결
